public class siteVotacionEDMController {
	/*
	public String user {get;set;}
	public String pass {get;set;}
	
	public PageReference login(){
	
	    return Site.login('admin@donmario.com', 'es2011','/apex/prueba_site' );
		
	}
	
	public PageReference init(){
	    
	    if (user == 'jarias' && pass == '123456'){
	        PageReference pr = new PageReference('/apex/CRM_NV');		    
		    return pr;   	
	    }else{
	    	ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Error');            
	        ApexPages.addMessage(msg); 
	        return null;
	    }
		
	}
*/
}